### ISSUE TITLE
Spotkanie

### ISSUE THREAD

**Issue by maartin25** [tomesh1991/pz_project#10]
Jest źle, projekt nie przeszedł. 
Nie mamy klientów! 
Jest tylko komunikacja z sensorami.
Spotkanie wszystkich po za ludźmi od sensorów w poniedziałek o 19 w alfie

**Comment by klotor90** [comment]
Dokładnie.

Druga rzecz jaką trzeba przegadać, to zmiana lidera. Nie dość, że nie mam na to czasu to jeszcze kompletnie nie umiem gonić ludzi do roboty :/. Trzeba machnąć jakieś głosowanie czy coś...

**Comment by koziolek90** [comment]
A czy zebranie w pon wcześniej komuś by kolidowalo? Tak kolo 17:30? Albo
ostatecznie o 18?
14 maj 2015 10:58 "klotor90" notifications@github.com napisał(a):

**Comment by tomesh1991** [comment]
Ja bym wolał zostać przy 19. 18 to ewentualnie najwcześniej.

**Comment by gqc3k** [comment]
Pasuje mi 19.

2015-05-14 11:01 GMT+02:00 tomesh1991 notifications@github.com:

> Ja bym wolał zostać przy 19. 18 to ewentualnie najwcześniej.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/tomesh1991/pz_project/issues/10#issuecomment-101978130
> .

## 

Z poważaniem,
Robert Gaca

**Comment by klotor90** [comment]
Jak dla mnie, to każda godzina od 17:30 jest ok

2015-05-14 11:35 GMT+02:00 gqc3k notifications@github.com:

**Comment by gqc3k** [comment]
Hej,

panowie sory że tak późno piszę ale może o 18 to spotkanie ? Pasuje wam czy
nie bardzo ?

W dniu 14 maja 2015 13:33 użytkownik klotor90 notifications@github.com
napisał:

> Jak dla mnie, to każda godzina od 17:30 jest ok
> 
> 2015-05-14 11:35 GMT+02:00 gqc3k notifications@github.com:
> 
> > Pasuje mi 19.
> > 
> > 2015-05-14 11:01 GMT+02:00 tomesh1991 notifications@github.com:
> > 
> > > Ja bym wolał zostać przy 19. 18 to ewentualnie najwcześniej.
> > > 
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <
> > 
> > https://github.com/tomesh1991/pz_project/issues/10#issuecomment-101978130>
> > 
> > > .
> > 
> > ## 
> > 
> > Z poważaniem,
> > Robert Gaca
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > <
> > https://github.com/tomesh1991/pz_project/issues/10#issuecomment-101984434>
> > 
> > .
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/tomesh1991/pz_project/issues/10#issuecomment-102008692
> .

## 

Z poważaniem,
Robert Gaca

**Comment by koziolek90** [comment]
Mi już teraz nie bardzo bo musze zostać do 18 w pracy
18 maj 2015 00:17 "gqc3k" notifications@github.com napisał(a):

**Comment by klotor90** [comment]
Dobrze, w takim razie 18:30?

W dniu 14 maja 2015 10:28 użytkownik Marcin notifications@github.com
napisał:

**Comment by koziolek90** [comment]
Ja dopiero na 19 się wyrobię
18 maj 2015 07:45 "klotor90" notifications@github.com napisał(a):

**Comment by maartin25** [comment]
Nie wiecie co z Rafałem, czy będzie?
Ma ktoś do niego kontakt?

**Comment by RafalKantor** [comment]
Będę dzisiaj
pzdr

2015-05-18 9:55 GMT+02:00 Marcin notifications@github.com:

**Comment by gqc3k** [comment]
To może nawet 18.30 najwyżej jak ktoś nie da rady to dojdzie na 19.  Muszę
gdzieś 19.20 wyjść najpóźnej.

2015-05-18 10:08 GMT+02:00 RafalKantor notifications@github.com:

> Będę dzisiaj
> pzdr
> 
> 2015-05-18 9:55 GMT+02:00 Marcin notifications@github.com:
> 
> > Nie wiecie co z Rafałem, czy będzie?
> > Ma ktoś do niego kontakt?
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > <
> > https://github.com/tomesh1991/pz_project/issues/10#issuecomment-102954923>
> > 
> > .
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/tomesh1991/pz_project/issues/10#issuecomment-102959755
> .

## 

Z poważaniem,
Robert Gaca

**Comment by tomesh1991** [comment]
Ja postaram się wyrobić na 18:30, ale jest większa szansa, ze będę w okolicach 19. Gdzie się będzie odbywać to spotkanie? Ja biegły w akademiku nie jestem, więc proszę o dokładne wytyczne. :)

**Comment by wbidus** [comment]
Czyli co, na 18.30 ostatecznie? Mi obojętne na którą. Byle się nie okazało że tylko ja przyjdę na 18.30 :}

**Comment by gqc3k** [comment]
Będę o 18.30

**Comment by koziolek90** [comment]
Ja będę tak jak pisałem o 18
18 maj 2015 16:46 "gqc3k" notifications@github.com napisał(a):

**Comment by koziolek90** [comment]
Poprawa! Będę i 19
18 maj 2015 16:57 napisał(a):

Ja będę tak jak pisałem o 18
18 maj 2015 16:46 "gqc3k" notifications@github.com napisał(a):

Będę o 18.30

**Comment by klotor90** [comment]
lektorium

2015-05-18 16:58 GMT+02:00 koziolek90 notifications@github.com:
