### ISSUE TITLE
Czyszczenie repozytorium z martwych gałęzi

### ISSUE THREAD

**Issue by GeredTa** [tomesh1991/pz_project#13]
Usunięte mają być gałęzie nieużywane

**Comment by GeredTa** [comment]
Pytanie do wszystkich szczególnie do gacy czy branch "Monitor gaca" jest jeszcze w użyciu czy gałąź jest martwa?

**Comment by GeredTa** [comment]
Zgodnie z brakiem odzewu. Gałąź zostaje usunięta a pliki trafiają do folderu Syf/Gaca na gałęzi monitor.

**Comment by gqc3k** [comment]
Można wywalić branch MonitorGaca - teraz obowiązująca jest tylko Monitor.

2015-05-28 13:49 GMT+02:00 GeredTa notifications@github.com:

> Zgodnie z brakiem odzewu. Gałąź zostaje usunięta a pliki trafiają do
> folderu Syf/Gaca na gałęzi monitor.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/tomesh1991/pz_project/issues/13#issuecomment-106288331
> .

## 

Z poważaniem,
Robert Gaca

**Comment by GeredTa** [comment]
Dobra jedziemy dalej. 
1. Co jest z branch'em AutoKlient - jest na nim rozwijane cokolwiek? Jeżeli nie to czy dane są do czegokolwiek wykorzystywane?
2. Wyrzucam folder stary syf z Monitora (nikt nie zgłosił żadnych pretensji do niego więc wydaje uznaje go za martwy kod)

**Comment by gqc3k** [comment]
Panowie to tak w skrócie, co mamy czego nie mamy ?
Co mamy do pokazania na jutrzejszym spotkaniu ?

ps. (propozycja) Weźmy się gdzieś spotkajmy może jutro wieczorem
ewentualnie na parę godzin zróbmy ten syf już do końca i miejmy spokój ?

robert

W dniu 28 maja 2015 14:18 użytkownik GeredTa notifications@github.com
napisał:

> Dobra jedziemy dalej.
> 1. Co jest z branch'em AutoKlient - jest na nim rozwijane cokolwiek?
> Jeżeli nie to czy dane są do czegokolwiek wykorzystywane?
> 2. Wyrzucam folder stary syf z Monitora (nikt nie zgłosił żadnych
> pretensji do niego więc wydaje uznaje go za martwy kod)
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/tomesh1991/pz_project/issues/13#issuecomment-106293404
> .

## 

Z poważaniem,
Robert Gaca

**Comment by wbidus** [comment]
Ja używam danych z autoklienta. Jak tylko skończę, scommituje tam. proszę nic nie usuwać.

**Comment by GeredTa** [comment]
Dobra jak skończysz napisz to zmerguje i przeniosę wszystko na jeden branch. A potem spróbuję to wszystko uruchomić... 

Ale będzie błędów

**Comment by wbidus** [comment]
Nie umiem zbytnio w gita, ale zdaje się że scommitowalem zmiany. juz nie będę nad tym siedział przed spotkaniem - co nie znaczy że jest już skończone. W każdym razie, można mergować.

**Comment by GeredTa** [comment]
Możesz zrobić tego pusha w do poniedziałku?

**Comment by wbidus** [comment]
Zrobiłem chyba dobrze teraz, a jesli coś skopałem to mam kopie tych plików. Możesz więc mergować jak będziesz miec chwile.

**Comment by GeredTa** [comment]
Dobra obecnie obowiązującą gałęzią jest Monitor (w sumie to jest to jedyna istniejąca gałąź poza master).
