### ISSUE TITLE
Uruchomienie sensora jako projekt visual studio.

### ISSUE THREAD

**Issue by klotor90** [tomesh1991/pz_project#16]
Trzeba podpiąć pythona pod projekt visuala. Będzie milej, szybciej, łatwiej i jednolicie.

Krzychu, wojuj.

**Comment by GeredTa** [comment]
Stworzone zostały dwa projekty visual studio 
- sensor
- responder
  oba są projektami python i do ich uruchominia potrzebny jest https://www.visualstudio.com/en-us/features/python-vs.aspx

Poza tym stworzona została solucja grupująca oba projkety.

Dawid zrób pula i ogarnij czy nie ma syndromu "u mnie działa". 
Jak jest ok, to zamknij ten issue i puść nowy "Połączenie kodu sensora i monitora" oraz "Zmiana dokumentacji w kwestii używanych narzędzi" przypisz je do mnie.

**Comment by klotor90** [comment]
U mnie działa :D
Trzeba tylko w opcjach projektów ustawić własnego interpretera pythona i będzie ok.
