### ISSUE TITLE
Połączenie kodu sensora i monitora

### ISSUE THREAD

**Issue by klotor90** [tomesh1991/pz_project#17]
Należy połączyć projekty sensora i monitora w jedno rozwiązanie VS.

Do boju :D

**Comment by GeredTa** [comment]
Merge jest zrobiony, ale mamy porządnego wała na repozytroium tj. usunięta zotała konfigarcja pakietów dla projektu PzProjekt.

Nie mogę kontynuwać, aż nie uruchomię projektu nad czym właśnie pracuje.

Tymaczesem robie push na gałęzi monitor po merg'u.

**Comment by GeredTa** [comment]
Ok problem z plikiem konfiguracyjnym packages.conf rozwiązany.

Zaraz przeniosę to do jednej solucji i powinno być dobrze :D

**Comment by GeredTa** [comment]
Dobra w gałęzi monitora wszystko działa i jest względnie uprzątnięte. Elementy z którymi nie wiedziałem co zrobić znajdują się w folderze stary syf, który ktoś musi przejrzeć i sprzątnąć zawartość.

Panie Skurewicz sprawdź Pan syndrom u mnie działa:
1. CleanUp na repozytorium (opcja tortoisa)
2. Checkout na Monitor
3. Pull
4. Uruchom wszystkie 3 projekty (Enable restore nuget package przed uruchominiem projektu c#)
5. Jak zadziała to zamknij  ticket powinno być ok.

**Comment by klotor90** [comment]
Zrobię to dzisiaj po pracy, wcześniej nie da rady.

Btw... SkUrewicz? serio? :P

2015-05-19 23:15 GMT+02:00 GeredTa notifications@github.com:

**Comment by GeredTa** [comment]
Tak - zgodnie z naszym dawnym kawałem s_k****

**Comment by klotor90** [comment]
Coś jest nie tak.

Co zrobiłem:

Debug:
1. CleanUp na repozytorium (opcja tortoisa)
2. Checkout na Monitor
3. Pull
4. Zmieniłem pythona na mój interpreter
5. Zmieniłem port sensora z 1548 na 52123
6. Uruchomiłem monitor - działa w przeglądarce
7. Uruchomiłem sensor - zfreezował i daje błąd w monitorze:
    >PzProj.dll!PzProj.Controllers.MeasurementsController.PostMeasurements(PzProj.Requests.MeasurementRequest item) Line 73
1. Dałem continue w monitorze - sensor wysłał pakiet i otrzymał odpowiedź 500 INTERNAL SERVER ERROR po czym monitor wyrzucił unhandled exception

Dodatkowo http://localhost:52123/api/measurements jest zapchane komunikatami o błędach sql i nie tylko. Punkt 8. można powtarzać jeśli będzie się klikało continue.
1. Responder ma problem z "odniesieniem się do portu do którego użycia zabraniają prawa dostępu" ale może to wynikać z zapchania portu przy niepoprawnym zamknięciu.

Projekty każdy z osobna zdaje się działać poprawnie.

Wniosek: chyba coś nie za dobrze z bazą danych :/

**Comment by GeredTa** [comment]
Ok wygląda na to że z repozytorium jest ok.

Co do błędów 
1. Sensor wysłał pakiet i otrzymał odpowiedź 500 INTERNAL SERVER ERROR po czym monitor wyrzucił unhandled exception. - to jest wina bazy danych (u mnie baza wogóle nie działa i wygląda jakby mi wogóle SQL serwer odwalał fazy, więc nie wiem specjalnie gdzie leży przyczyna. Tak czy inaczej sensor nie sypie się po błędzie więc jest ok. Przynajmniej dla mnie.
2. Drugiego błędu nie mogę powtórzyć czyli najprawdopodobniej jest jak opisałeś z tą różnicą że u mnie zwolniło zasoby

**Comment by maartin25** [comment]
Błąd może być spowodowany tym że sensor jest niezarejstrowany.
Rejestrowanie  jest w tabeli SimpleMeasureType pod unique_sensor_id.
Wartości inicjalizacyjne są wpisane w klasie Confguration.

Sensor zgodnie z założeniami ma unikalny id który się nie zmienia nigdy.
Nawet po ponownym uruchomieniu i na innym hoscie. Po tym rozpoznajemy co mierzy sensor.
Sensor do RAM ma id 2568157.

Jeśli to nie jest ustawione w sensorze jeszcze to trzeba to zgrać tu i tu

**Comment by maartin25** [comment]
W razie czego każdą metodę można debugować w kontrolerze

**Comment by GeredTa** [comment]
Wątek dotyczy samego scalenia kodu sensora i monitora - a to zostało zrobione. Ponieważ w końcu udało mi się ogarnąć bazę lokalną sprawdzę jeszcze raz połączenie Sensor - Monitor. Jak się wysypie to Dawid dostaniesz ticket'a do obrobienia.
