### ISSUE TITLE
Spotkanie projektowe z p. Balisiem

### ISSUE THREAD

**Issue by klotor90** [tomesh1991/pz_project#19]

**Comment by klotor90** [comment]
Panowie,
znow nie ogarnalem, ze dostalismy info od prowadzacego.

terminy spotkania z projektem w koncowej fazie (rozmawialismy o tym wczoraj) to:
sroda 11:15
czwartek 10:00
piatek 7:40 (tutaj tylko do 8:00)

Wypowiedzcie sie co wam najbardziej pasuje i wybierzmy jeden termin. Mysle, ze jutro odpada w przedbiegach...

I jeszcze jedno, ustalmy to dzisiaj jesli sie uda.

**Comment by GeredTa** [comment]
Mnie nie ma i nie będzie w krk ale to chyba wiadomo

**Comment by klotor90** [comment]
Tak, o Tobie wiem.
 19 maj 2015 21:50 "GeredTa" notifications@github.com napisał(a):

**Comment by lpawlik91** [comment]
piatek 7:40 jak juz

**Comment by klotor90** [comment]
Dzisiaj o 17:00 wysyłam wiadomość, ze pasuje nam piątek, jak ktoś ma coś rpzciwko to niech się spręży z odpowiedzią!

**Comment by gqc3k** [comment]
Hej. nie dam rady w piatek ! .... mialem wracac dzisiaj juz do siebie musze
byc w tygodniu u siebie (Przemyśl) mam tam jakies sprawy, mialem wraca
dzisaij ale chcialem zostac do jutra zeby byc rano i od razu wracac. Co do
piatku to slabo nie ogarne :/.

W dniu 20 maja 2015 13:55 użytkownik klotor90 notifications@github.com
napisał:

> Dzisiaj o 17:00 wysyłam wiadomość, ze pasuje nam piątek, jak ktoś ma coś
> rpzciwko to niech się spręży z odpowiedzią!
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/tomesh1991/pz_project/issues/19#issuecomment-103857717
> .

## 

Z poważaniem,
Robert Gaca

**Comment by koziolek90** [comment]
Mi na razie ciężko powiedzieć bo wdrazam projekt w czwartek i piątek i
musze ogarnąć czy mogę przyjść później do pracy
20 maj 2015 13:57 "gqc3k" notifications@github.com napisał(a):

**Comment by klotor90** [comment]
No dobrze, chcę żeby przynajmniej jedna osoba z każdej części (klient auto, klient web, monitor, sensor <ja>) była na tym spotkaniu. Im nas więcej tym lepiej. Koziolek90 - to spotkanie w piątek trwałoby max 20 minut. o 8:00 byłbyś wolny.

**Comment by koziolek90** [comment]
Wiem ale mam godzinę dojazdu :/
20 maj 2015 14:49 "klotor90" notifications@github.com napisał(a):

**Comment by klotor90** [comment]
Znam ten ból, jeżdżę do niepołomic.

Dajcie znać DO DZISIAJ DO 20, bo muszę coś wysłać.

**Comment by koziolek90** [comment]
Ja nie dam rady,  jeszcze przed chwilą dzwonili z mala zmiana a na piątek
ma być wdrożone :/
20 maj 2015 16:51 "klotor90" notifications@github.com napisał(a):

**Comment by RafalKantor** [comment]
Piątek oczywiście i jako że jestem jednym z tych odpowiedzialnych za
opóźnienie to będę na pewno.

W dniu 20 maja 2015 17:41 użytkownik koziolek90 notifications@github.com
napisał:

**Comment by klotor90** [comment]
Dobrze, wysyłam maila, że spotykamy się 7:40 w piątek. 

Bądźcie 7:30!!!

**Comment by RafalKantor** [comment]
Jeszcze gdzie ? w nowym budynku infy na 3 piętrze?

2015-05-20 19:10 GMT+02:00 klotor90 notifications@github.com:

**Comment by klotor90** [comment]
tak

**Comment by maartin25** [comment]
Na ostatnim spotkaniu dr Balis przypomniał że jest pare spotkań obowiązkowych. (na których mają być wszyscy) i z drugiej grupy widziałem że wszyscy byli. Jutrzejesze z tego co wiem takie jest, Kto nie może przyjść niech najlepiej osobiście napisze do niego.

**Comment by gqc3k** [comment]
Plany mi się zmieniły i będę jutro. Godzina śmierć ale postaram się ! Do
jutra.

W dniu 21 maja 2015 23:10 użytkownik Marcin notifications@github.com
napisał:

> Na ostatnim spotkaniu dr Balis przypomniał że jest pare spotkań
> obowiązkowych. (na których mają być wszyscy) i z drugiej grupy widziałem że
> wszyscy byli. Jutrzejesze z tego co wiem takie jest, Kto nie może przyjść
> niech najlepiej osobiście napisze do niego.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/tomesh1991/pz_project/issues/19#issuecomment-104421111
> .

## 

Z poważaniem,
Robert Gaca

**Comment by klotor90** [comment]
Genialnie :D
21 maj 2015 23:44, "gqc3k" notifications@github.com napisał(a):

**Comment by GeredTa** [comment]
Dobra mamy kolejny tydzień - Zamykam
