### ISSUE TITLE
Baza monitora nie działa?

### ISSUE THREAD

**Issue by wbidus** [tomesh1991/pz_project#20]
Odpala się wam monitor w aktualnej wersji? U mnie wali error:  EntityType 'AdvanceMeasure' has no key defined. Define the key for this  w momencie budowania bazy

**Comment by GeredTa** [comment]
Zassałeś nową wersję z repozytorium - push z przed jakiś 20 min?

**Comment by wbidus** [comment]
Tak.

**Comment by GeredTa** [comment]
1. Upewnij się że jesteś na gałęzi monitora
2.  CleanUp na repozytorium (opcja tortoisa)
3.   Uruchom przez solucje PZ_Solution
4.  menu kontekstowe solucji / Enable restore nuget package
5. Run

**Comment by wbidus** [comment]
Pakiety nugeta mi wszystkie pobralo bo sie builduje dobrze. Problem występuje w momencie gdy:
a) robię zapytanie o hosty
b) robie update-database

**Comment by GeredTa** [comment]
Fuck rzeczywiście coś się sypie, tyle że w runtime. Obawiam się, że jedyną osobą, która ogarnia tą część systemu jest Marcin. Przypiszę pytanie do niego, a w między czasie poszukam rozwiązania na własną rękę. Niestety nie licz na zbyt wiele z mojej strony tylko raz w życiu używałem entity relationship w c# więc to może potrwać. Pomijając kwetie błędu - piszesz w tej chwili klienta desktopowego tak?

**Comment by wbidus** [comment]
Może nie w tej chwili, ale tak.

**Comment by maartin25** [comment]
pull
update-database -force -verbose w razie potrzeby
jak i to nie pójdzie drop database

**Comment by klotor90** [comment]
U mnie w ogóle nie ma bazy, nie ma się z czym łączyć, samo jej nie produkuje.

**Comment by maartin25** [comment]
Nazwę serwera trzeba ustawić w WebConfig, tam gdzie można wepchnąć bazę.
Z tego co kojarzę to większość osób ma serwer LocalDB.
Wojtek, jakiego Ty masz configa dla takiego servera i vs2013?

**Comment by RafalKantor** [comment]
<add name="PzProjContext" connectionString="Data Source=(LocalDB)\v11.0;
Initial Catalog=PzProjDB2; Integrated Security=True;
MultipleActiveResultSets=True;
AttachDbFilename=|DataDirectory|PzProj-20140613003603.mdf"
providerName="System.Data.SqlClient" />

update-database -force -verbose

U mnie zmiana DataSource na jak powyżej i Initial Catalog  na jakikolwiek
inny  a następnie wykonanie powyższej komendy pozwoliło połączyć sięz bazą
danych a miałem ten sam problem.

pzdr

W dniu 20 maja 2015 18:49 użytkownik Marcin notifications@github.com
napisał:

**Comment by GeredTa** [comment]
Teoretycznie opracowałem algorytm usuwający problem z bazą danych (instrukcja dla visual studio ultimate 2013):

Znalezienie connection string dla Web.cofig, czyli co wstawić w

```
<connectionStrings>;
<add name="PzProjContext" connectionString="..." providerName="System.Data.SqlClient"/>
<connectionStrings>;
```
1. Menu View/Server Explorer
2. Menu View/SQL Server Object Explorer
3. Powyższe dwie operacje otwierają okna explorera serwera i SQL
4. (okno SQL explorer) Menu kontekstowe dla istniejącego serwera sql/Properties
5. Properties opisany jako connection string zawiera działające dane. Dla mnie jest to coś w stylu "Data Source=(localdb)\ProjectsV12;Initial Catalog=master;Integrated Security=True;Connect Timeout=30;Encrypt=False;TrustServerCertificate=False"
6. Menu View/Other Windows/Package Manager Console
7. W nowo otwarte okno wpisać "update-database -force -verbose" (nie mam pojęcia, dlaczego działa u mnie tylko z tej konkretnej konsoli — podejrzewam dziwności power shell dla visuala.)
8. Odpalić projekt monitora.

Powyższa metoda działa, ale jestem na 99% pewny, że connection string nie chodzi dokładnie tak, jak byśmy tego sobie życzyli np. Initial Catalog=master; - śmierdzi mi syfieniem w systemie. Niestety nie znam się na połączeniach SQL/net, więc nie wiem, co oznaczają poszczególne opcje.

Nie sprawdzałem czy metoda naprawia problem z połączeniem senosor - monitor, o którym pisał Dawid w innym wątku. Zaraz się tym zajmę.

**Comment by maartin25** [comment]
Initial Catalog to chyba może być cokolwiek. To jest nazwa bazy danych jaka zostanie utworzona, Na sql server express tak jest. Z localDb nie korzystałem

**Comment by GeredTa** [comment]
Zamykam wątek ponieważ wygląda na martwy. Istniejąca instrukcja została przeniesiona do wiki (zakładka baza danych).
