### ISSUE TITLE
Senor nie współpracuje z monitorem

### ISSUE THREAD

**Issue by GeredTa** [tomesh1991/pz_project#22]
Komunikat response to 400 zamiast 200;

Dawid czy poniższy JSON jest spełniony dla POST

```
{
  "Host": {
    "name": "sample string 1",
    "unique_id": 2
  },
  "SensorUniqueId": 1,
  "Value": 2
}
```

Jeżeli tak to czy spełnione są dodatkowe założenia:
1. unique_id jest tym generowanym z płyty głównej id
2. SensorUniqueId jest wartością sztywną 1 lub 2 w zależności czy mierzymy procka czy RAM

**Comment by wbidus** [comment]
Kurde, też odpaliłem teraz ten sensor - nie wiem jaki jest response dokładnie, ale widzę że mi się rekordy żadne do bazy nie dodają mimo że jest odpalona już prawidłowo... Przynajmniej gety cały czas zwracają to samo, mimo że odczyty powinny się pojawić nowe.

edit. 400.

**Comment by maartin25** [comment]
Jest zły SensorUniqueId ma być on taki jak w SimpleMeasureType.unique_sensor_id. Wartość inicjalizyacyjna jest w klasie Configuration. I dla RAM jest to 2568157. 
Pisałem o tym w #17

**Comment by GeredTa** [comment]
Walnąłem hotfixa. U mnie działa, tyle że wartości są zahardkodowane w sensorze, więc Dawid powinien to poprawić tak by miało ręce i nogi.

**Comment by klotor90** [comment]
Momento moria, host ID miał być generowany z płyty głównej i tak jest, dla każdego kompa będzie inny.
Sensor ID jest unikalnym ID sensora, nie wskazuje na to, czy to ram czy CPU.

Napiszcie mi tutaj:
1. Jakie ma być ID sensora dla RAM
2. Jakie ma być ID sensora dla CPU
3. Jakie mają być ID hostów (hardkodowane, generowane?) bo teraz już się pogubiłem.

JSon jest spełniony.

**Comment by maartin25** [comment]
1. Ram 2568157 - zahardcodowane w sensorze
2. CPU 12321 - zahardcodowane w sensorze
3. id hosta uid płyty. Sprzętowy identyfikator niezmienny dla hosta. Możę być też mac ale uid był by najlepszy

**Comment by klotor90** [comment]
1. jest zrobione

zaraz spróbuję pullnąć sensor w pracy i zrobić fixa do 1 i 2

**Comment by klotor90** [comment]
Edit: nie 1 tylko 3, durny edytor githuba :/

**Comment by klotor90** [comment]
Ten hotfix wygląda ok, jeśli wam to działa to ja już nei będe nic commitował.
Edit: Krzychu, tak to chyba ma być jak zrobiłeś :D
Edit2: Zmieniać port z 1548 na 52345?

**Comment by GeredTa** [comment]
Monitor i sensor działają zamykam wątek

**Comment by wbidus** [comment]
Działają, ale czy poprawnie? U mnie rzeczywiście odpowiedzi na sensorze są 200, ale robiąc get na wszystkich hosts, nie widzę żeby pojawił się nowy SUPAKOMPJUTA czy tam jego id. W measurements też nie ma nowych pomiarów które są niby odbierane.

**Comment by GeredTa** [comment]
Z tego co się orientuję task jest martwy od tygodnia
