### ISSUE TITLE
Projekt Monitor_Kl2 w gałęzi AutoKlient się nie kompiluje

### ISSUE THREAD

**Issue by GeredTa** [tomesh1991/pz_project#25]
Podejrzewam,  że to jest projekt klienta automatycznego jednak się nie kompiluje.

Plik:  MonitorHosts.cs
Błąd: using Monitor_kl2.Connection; - ten namespace nie istnieje, podobnie jak plik i klasa o tej nazwie

Wojtek sprawdź jeszcze raz czy na pewno zrobiłeś poprawnego pusha, ewentualnie popraw mnie jeżeli czegoś nie ogarnąłem.

**Comment by wbidus** [comment]
No to wrzuciłem teraz pliki projektu (jakiś nowy folder w projekcie), powinno chyba działać...

**Comment by GeredTa** [comment]
Dobra tym razem jest ok
