### ISSUE TITLE
Projekt GUI

### ISSUE THREAD

**Issue by klotor90** [tomesh1991/pz_project#4]
Projekt GUI musi powstać do środy wieczorem (24-03-2015). Potrzebna nam wersja wstępna, do późniejszych zmian.

**Comment by wbidus** [comment]
Wut. Jaki projekt gui. Jeszcze funkcjonalności przecież nie ma nawet dobrze określonych. poważnie gui potrzebujesz? Zbyt wiele to tam nie bedzie. no ale dobra.

**Comment by klotor90** [comment]
Czytałeś maila od prowadzącego? ^^

**Comment by wbidus** [comment]
Oczywiście. Musiałem przeoczyć :)

**Comment by gqc3k** [comment]
Hej,

to suma summarum na czym stanęło z MONITOREM ?

.net  czy java ?

paczał ktoś na te licencje itd... ?

robert

W dniu 25 marca 2015 17:39 użytkownik wbidus notifications@github.com
napisał:

> Oczywiście. Musiałem przeoczyć :)
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/tomesh1991/pz_project/issues/4#issuecomment-86110586.

## 

Z poważaniem,
Robert Gaca

**Comment by koziolek90** [comment]
Stanęło juz podczas rozmowy na .Net

**Comment by gqc3k** [comment]
Ciao,
dopisałem coś tam do monitora  -  mam cichą nadzieję, że ma to ładnie tylko
wyglądać na papierze i jeżeli finalny (  (  ) efekt będzie różnił się od
danych
w dokumentacji to de fakto nic złego się nie stanie i potraktowane to
zostanie jako, dobre założenie ale .... nie wyszło. Nie wiem czy na tym
etapie to mają być tylko załozenia czy już działające API ? .... trochę
szybko na to chyba.
Najszybciej jak coś to na weekendzie coś popiszę (pouczę się .net-a).

buziaczki

W dniu 25 marca 2015 18:28 użytkownik koziolek90 notifications@github.com
napisał:

> Stanęło juz podczas rozmowy na .Net
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/tomesh1991/pz_project/issues/4#issuecomment-86132273.

## 

Z poważaniem,
Robert Gaca

**Comment by wbidus** [comment]
Wrzuciłbym mój artwork tutaj, ale nie mam w tej chwili dostępu do swojego ftp. Mogę tu gdzieś wrzucić fotke i zalinkować ją na wiki?

edit. Nie wiem jak, ale jakoś wrzuciłem obrazki (wraz z opisem, na wiki). Na nic lepszego nie ma co liczyć, nie chce mi się ich robić w paincie bo to szkoda czasu - jak będziemy mieć lepszą wizję jak to będzie działać, to i projekt GUI będzie lepszy.
