### ISSUE TITLE
Używane narzędzia

### ISSUE THREAD

**Issue by GeredTa** [tomesh1991/pz_project#5]
Dobra chłopaki trzeba ogarnąć co i w czym piszemy. Pomijając już rzekomy brak API i GUI :)

Stworzyłem repozytorium i wrzuciłem tam materiały Balisia i trzeba by było ogarnąć narzędzia, których używamy i je poinstalować ewentualnie.

Moje propozycje:
1. C# - Microsoft Visual Studio Ultimate 2013 (chyba, że jest nowszy) - do pobrania z dream spark.
2. UML - Lucid chart https://www.lucidchart.com/
3. Reszta dokumnetacji - wiki jest trochę mało wygondna (jak dla mnie), wolałbym przejść na Latex (np. miktex + TexMaker | http://miktex.org/ + http://www.xm1math.net/texmaker/)
4. Python - Do decyzji Dawida bo on to ogarnia.
5.C/C++ - słyszałem, że coś miało być w C/C++, ale nie widzę do tego w dokumentacji (może nie wiem gdzie patrzeć). Tak czy inaczej patrząc na problematykę odradzam używanie tego języka (choć jestem jego zagorzałym fanatykiem). Jeżeli jednak będziemy pisać w cepie to proponyję po raz kolejny Visual Studio (i tak już go używamy).

Jak coś pominąłem to niech zainteresowani dopiszą się do listy:
1. Microsoft Visual Studio Ultimate 2013 
2 Lucid chart - https://www.lucidchart.com/
3. miktex + TexMaker | http://miktex.org/ + http://www.xm1math.net/texmaker/

PS.

Jak macie jakiekolwiek prototypy czegokolwiek to wrzućcie to do repozytorium.

**Comment by tomesh1991** [comment]
Jeśli chodzi o bazę danych, to osobiście preferuję MySQL ze względu na większą liczbę hostingów oraz lepszych jego warunków (jedyne znalezione przeze mnie z darmowym MSSQL: https://somee.com/default.aspx - baza MSSQL - 15 MB O.o). Może wystarczyć, ale bardzo możliwe, że nie jest ona dostępna ze świata. 

Tworząc maszynę wirtualną na swoim sprzęcie omijam problem ograniczeń sprzętowych, ale powraca problem dostępności dla reszty z Was.

**Comment by wbidus** [comment]
Ja już się przesiadłem na visual studio community 2013. Chyba mu nic nie brakuje.

**Comment by klotor90** [comment]
Do pisania sensorów używałem pythona 3.4.3 i środowiska pyCharm community edition.

**Comment by GeredTa** [comment]
1. Microsoft Visual Studio Ultimate 2013/visual studio community 2013 (oba działają poprawnie)
2. Lucid chart - https://www.lucidchart.com/
3. miktex + TexMaker | http://miktex.org/ + http://www.xm1math.net/texmaker/
4. python 3.4.3
5. pyCharm community edition (https://www.jetbrains.com/pycharm/download/)

**Comment by GeredTa** [comment]
1. Microsoft Visual Studio Ultimate 2013/visual studio community 2013 (oba działają poprawnie)
2. Lucid chart - https://www.lucidchart.com/
3. miktex + TexMaker | http://miktex.org/ + http://www.xm1math.net/texmaker/
4. python 3.4.3
5. pyCharm community edition (https://www.jetbrains.com/pycharm/download/)
6. git - https://git-scm.com/downloads
7. tortoise git - https://code.google.com/p/tortoisegit/

**Comment by GeredTa** [comment]
1. Microsoft Visual Studio Ultimate 2013/visual studio community 2013 (oba działają poprawnie)
2. Lucid chart - https://www.lucidchart.com/
3. miktex + TexMaker | http://miktex.org/ + http://www.xm1math.net/texmaker/
4. python 3.4.3 - https://www.python.org/downloads/release/python-343/
5. python for visual studio - https://www.visualstudio.com/en-us/features/python-vs.aspx
6. git - https://git-scm.com/downloads
7. tortoise git - https://code.google.com/p/tortoisegit/
