### ISSUE TITLE
Wszysko w REST

### ISSUE THREAD

**Issue by maartin25** [tomesh1991/pz_project#6]
Aktualnie używamy WebApi do monitora który wspiera tylko HTTP. Działa wyświetlanie danych i zapis, baza jest jak narazie tworzona automatycznie, ale to nie problem przepiąć, jest też fajna dokumentacja, można łatwo dodać logowanie. I nawet to działa. 
Jeśli chcemy szybko monitor skończyć to było by najlepiej przejść na REST. Co do klienta web i automatycznego to nie będzie problem.
 Zostaje tylko kwestia sensorów które musiały by zrobić POST'a. Co Wy na to?
Innym wyjściem jest przejście w monitorze na WCF.

**Comment by gqc3k** [comment]
Hej,

Aktualnie używamy WebApi do monitora który wspiera tylko HTTP.

Mówisz teraz o tym co miał Dawid na spotkaniu z Balisiem ?
Wysłałem mu zmieniony projekt (baza jest tam w pliku i zaciągana do api a
nie tworzona w migrations) - zaraz zrobie pusha na serwer tej wersji.

Jeśli chcemy szybko monitor skończyć to było by najlepiej przejść na REST

Tzn ? Co jest w tym momencie, a do czego dążymy ? (sory ale jestem świeży w
.Net ;D)

Innym wyjściem jest przejście w monitorze na WCF.

j.w.

robert

W dniu 23 kwietnia 2015 11:38 użytkownik Marcin notifications@github.com
napisał:

> Aktualnie używamy WebApi do monitora który wspiera tylko HTTP. Działa
> wyświetlanie danych i zapis, baza jest jak narazie tworzona automatycznie,
> ale to nie problem przepiąć, jest też fajna dokumentacja, można łatwo dodać
> logowanie. I nawet to działa.
> Jeśli chcemy szybko monitor skończyć to było by najlepiej przejść na REST.
> Co do klienta web i automatycznego to nie będzie problem.
> Zostaje tylko kwestia sensorów które musiały by zrobić PUSH'a. Co Wy na to?
> Innym wyjściem jest przejście w monitorze na WCF.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/tomesh1991/pz_project/issues/6.

## 

Z poważaniem,
Robert Gaca

**Comment by maartin25** [comment]
W tym momencie możemy tylko przez http/https gadać z monitorem bo WebApi nie wspiera UDP.
W specyfikacji jest narysowane że sensory po UDP gadają, ale to jest tylko sugestia z tego co zrozumiałem. Jak chcemy obsłużyć UDP to musimy użyć WCF. Trzeba było by zaimplementować funkcjonalność z kontrolerów WebApi do serwisu WCF, ogólnie z WCF-em jest z tego co wiem więcej zachodu. Ale sam też nie korzystałem.
Podeślij co dodałeś

**Comment by gqc3k** [comment]
Hej

Link do tego co mam popchnac na gita

https://www.dropbox.com/s/ggfkaakmchna2vw/WebApiPZ.rar?dl=0

Robert
23 kwi 2015 15:40 "Marcin" notifications@github.com napisał(a):

**Comment by koziolek90** [comment]
Kiedy będziesz to pushował do gita? Jak już to ogarniemy to tak jak pisał Dawid, trzeba zrobić spotkanie żeby ustalić kto, które funkcje pisze w api.

**Comment by gqc3k** [comment]
Poszedł push, sorry ale przed sekundą wróciłem na mieszkanie a wcześniej
wyleciało mi to z głowy.

W dniu 23 kwietnia 2015 22:19 użytkownik koziolek90 <
notifications@github.com> napisał:

> Kiedy będziesz to pushował do gita? Jak już to ogarniemy to tak jak pisał
> Dawid, trzeba zrobić spotkanie żeby ustalić kto, które funkcje pisze w api.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/tomesh1991/pz_project/issues/6#issuecomment-95707783.

## 

Z poważaniem,
Robert Gaca

**Comment by maartin25** [comment]
Wg mnie zostało zrobić autoryzacje, i nie ma w specyfikacji określone jak, więc można zrobić np tak jak tutaj: http://www.asp.net/web-api/overview/security/individual-accounts-in-web-api

I jeśli API będzie działać a na poprzedniej wersji z tego co widziałem coś działało, to będzie ok. 
Chyba że chcemy żeby każdy klient gadał inaczej i sensory przez UDP to wtedy jest więcej roboty i już nie zrobimy tego na WebApi.
Tak że ponawiam pytanie co z UDP?
