### ISSUE TITLE
Spotkanie DZIŚ

### ISSUE THREAD

**Issue by maartin25** [tomesh1991/pz_project#7]
Jak w temacie, kto dałby radę najlepiej w akademiku o 20:00
?

**Comment by koziolek90** [comment]
Ja dzisiaj nie mogę
27 kwi 2015 11:45 "Marcin" notifications@github.com napisał(a):

**Comment by maartin25** [comment]
ok, Chodzi o wszystkie osoby nie tylko odpowiedzialne za monitor

**Comment by gqc3k** [comment]
Hej,

dam rade jeżeli reszta się określi (pozytywnie ofkorz)

2015-04-27 12:05 GMT+02:00 Marcin notifications@github.com:

> ok, Chodzi o wszystkie osoby nie tylko odpowiedzialne za monitor
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/tomesh1991/pz_project/issues/7#issuecomment-96591498.

## 

Z poważaniem,
Robert Gaca

**Comment by wbidus** [comment]
Ja mogę wpaść spoko

W dniu 27 kwietnia 2015 13:39 użytkownik gqc3k notifications@github.com
napisał:

**Comment by tomesh1991** [comment]
Ja też nie dam rady dzisiaj się spotkać.
